### PR TITLE
Prevent using arrow keys to look when horizontal look is disabled

### PR DESCRIPTION
**Pull request by tmob03**
just a shrimple way to stop arrow key use

Not totally prevented since you can just -right or -left in console to stop it, but i mean you can also just change m_yaw during it too :p

### CODE REVIEW

**Comment by Pinsplash** [comment]
hrmmm i think the code for +left and +right is in the sdk tho

**Comment by tmob03** [comment]
IN_RIGHT and IN_LEFT button bits dont seem to work i already tried

**Comment by tmob03** [comment]
maybe im just dumb but like `pPlayer->ForceButtons(IN_DUCK);` worked whereas IN_LEFT and IN_RIGHT has no effect /shrug

**Comment by Pinsplash** [comment]
f1x3d

**Pull request closed without merging**
