### PR TITLE
Add twitch vote integration

### PR DESCRIPTION
**Pull request by acuifex**
The game side code is a disaster that needs a rewrite, but it works.

OBS client _should_ be able to support any number of effect votes.

OBS client supports changing votes.

OBS client doesn't yet support changing vote keywords for each vote, but doing that shouldn't be too hard.

This will partially address #2

### CODE REVIEW

**Comment by Pinsplash** [comment]
So exactly how ready to go is the twitch code? I can see some localhost references

**Comment by acuifex** [comment]
i'd say that it's decent.

it's using [pyTwitchAPI](https://github.com/Teekeks/pyTwitchAPI) for all of the api handling, which launches a localhost webserver to receive a token from twitch.

**Comment by Pinsplash** [comment]
Still needs a prompt of some kind for the voting options, doesn't it?

**Comment by acuifex** [comment]
It displays the options in the obs text source, and reads chat for keywords for voting.

There is probably a better way to do this for twitch, but i'm not familiar with that platform (~4 hours of total use time lol)

**Comment by Pinsplash** [comment]
So every user has to do all the steps in the readme right? And won't they have to edit the py file as it currently stands, since it references your own username?

**Comment by acuifex** [comment]
Yes, every streamer would have to install the plugin. No, unless they want to change the formatting (i haven't made it an option yet).

They don't have to do every step every time, but i haven't mentioned it in the readme, because i don't account for stupidity.

image

**Pull request merged**
