### PR TITLE
Youtube integration

### PR DESCRIPTION
**Pull request by holy-jesus**
#36

### CODE REVIEW

**Comment by acuifex** [comment]
> Accidentally pushed only youtube_integration.py in previous commit.

You can `git commit --amend` to change your last commit. Can be useful for situations like this.

**Comment by Pinsplash** [comment]
seen it but it will be a while before i can test

**Comment by Pinsplash** [comment]
so how does the setup compare to the twitch integration?

**Comment by Pinsplash** [comment]
still going to merge, with the caveat of no multistreaming for now

**Pull request merged**
