### PR TITLE
Fix compiling on Linux

### PR DESCRIPTION
**Pull request by ACBob**
I've been able to get it compiled, no idea if it runs properly or not, don't have HL2 Installed yet (and decided to fix/compile while I waited!)

### CODE REVIEW

**Comment by acuifex** [comment]
i'm pretty sure tier2.a, tier3.a libtier0.a and some other bins are required for compiling, since valve doesn't supply sources for those bins

**Comment by ACBob** [comment]
That sounds about right, but it worked on my machine so I'm unsure... I only removed the .a files, didn't touch the .so files.

**Comment by ACBob** [comment]
oh - I feel like a dunce, I didn't run a clean build...

**Comment by acuifex** [comment]
Now the bins are different. I think you should be changing the old commits and force pushing.

**Comment by Pinsplash** [comment]
what's with the changes in hl2_player.h and triggers.cpp/h?

**Comment by ACBob** [comment]
CChaosEffect wasn't found when compiling, needed by [this line](https://github.com/Pinsplash/halflife2chaos/blob/3d8b9cb5b106ee219c1e0b3a15f09193e705700d/sp/src/game/server/hl2/hl2_player.h#L91), and without externing `g_bEndSolidTriggers` it causes linker issues with multiple definitions. Doesn't seem to affect windows with the `#pragma once`.

**Comment by Pinsplash** [comment]
alright then, also commenting out the cbase.h line causes errors on windows

**Comment by ACBob** [comment]
Ah, my bad. I'll take a closer look at what the errors being produced actually are..

**Comment by Pinsplash** [comment]
bad gnews
image

**Comment by ACBob** [comment]
source is magical, I remember why I stopped touching it

**Comment by ACBob** [comment]
no idea if anything I did caused that, I didn't touch that script or anything that command relies on...

**Comment by Pinsplash** [comment]
it definitely was caused by that, started at that exact moment

**Comment by Pinsplash** [comment]
unexpected #endif where you put the preprocessor bit in hl2_player.cpp. weird

**Comment by ACBob** [comment]
there's not a bin\gnu in the base source sdk 2013, what the hell is going on

**Comment by Pinsplash** [comment]
sorry wait am dumb, didn't regenerate vpc. seems to work now

**Comment by Pinsplash** [comment]
nope, still having an unexpected #endif

**Comment by ACBob** [comment]
source moment

**Comment by Pinsplash** [comment]
yeah idk what to do about that. look into the linux errors i guess?

**Comment by acuifex** [comment]
> nope, still having an unexpected #endif

could this possibly be due to a different endline format? (i.e. \n instead of \r\n)

**Comment by Pinsplash** [comment]
i looked it up. using #ifdef like that is apparently not proper

**Comment by ACBob** [comment]
I'll look into it later, rough gist of the error is that it complains about something inside of STD headers and it's a massive include path to get there, it's all sphagetti

**Pull request merged**
